"""create initial ddf schema

Revision ID: 71b06b4139c9
Revises: 
Create Date: 2026-08-13 13:29:03.975476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b06b4139c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorities',
    sa.Column('authority_id', sa.String(length=256), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=256), nullable=False),
    sa.Column('sponsor', sa.String(length=256), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('resources', sa.JSON(), nullable=False),
    sa.Column('purposes', sa.JSON(), nullable=False),
    sa.Column('authority_path', sa.JSON(), nullable=False),
    sa.Column('constraints_json', sa.JSON(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parent_authority_id', sa.String(length=256), nullable=True),
    sa.Column('holder_public_key', sa.Text(), nullable=False),
    sa.Column('proof_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_authority_id'], ['authorities.authority_id'], ),
    sa.PrimaryKeyConstraint('authority_id')
    )
    op.create_index('idx_authority_actor', 'authorities', ['actor'], unique=False)
    op.create_index('idx_authority_expires_at', 'authorities', ['expires_at'], unique=False)
    op.create_index('idx_authority_issued_at', 'authorities', ['issued_at'], unique=False)
    op.create_index('idx_authority_sponsor', 'authorities', ['sponsor'], unique=False)
    op.create_index(op.f('ix_authorities_actor'), 'authorities', ['actor'], unique=False)
    op.create_index(op.f('ix_authorities_expires_at'), 'authorities', ['expires_at'], unique=False)
    op.create_index(op.f('ix_authorities_issued_at'), 'authorities', ['issued_at'], unique=False)
    op.create_index(op.f('ix_authorities_sponsor'), 'authorities', ['sponsor'], unique=False)
    op.create_table('authorization_logs',
    sa.Column('decision_id', sa.String(length=256), nullable=False),
    sa.Column('actor', sa.String(length=256), nullable=False),
    sa.Column('action', sa.String(length=256), nullable=False),
    sa.Column('resource', sa.String(length=512), nullable=False),
    sa.Column('purpose', sa.String(length=256), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('authority_id', sa.String(length=256), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index('idx_authlog_action', 'authorization_logs', ['action'], unique=False)
    op.create_index('idx_authlog_actor', 'authorization_logs', ['actor'], unique=False)
    op.create_index('idx_authlog_created_at', 'authorization_logs', ['created_at'], unique=False)
    op.create_index('idx_authlog_decision', 'authorization_logs', ['decision'], unique=False)
    op.create_index('idx_authlog_resource', 'authorization_logs', ['resource'], unique=False)
    op.create_index(op.f('ix_authorization_logs_action'), 'authorization_logs', ['action'], unique=False)
    op.create_index(op.f('ix_authorization_logs_actor'), 'authorization_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_authorization_logs_created_at'), 'authorization_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_authorization_logs_resource'), 'authorization_logs', ['resource'], unique=False)
    op.create_table('identities',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('identity_type', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_created_at', 'identities', ['created_at'], unique=False)
    op.create_index('idx_identity_type', 'identities', ['identity_type'], unique=False)
    op.create_table('provenance_events',
    sa.Column('event_id', sa.String(length=256), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('authority_id', sa.String(length=256), nullable=True),
    sa.Column('actor', sa.String(length=256), nullable=True),
    sa.Column('sponsor', sa.String(length=256), nullable=True),
    sa.Column('action', sa.String(length=256), nullable=True),
    sa.Column('resource', sa.String(length=512), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_provenance_actor', 'provenance_events', ['actor'], unique=False)
    op.create_index('idx_provenance_authority', 'provenance_events', ['authority_id'], unique=False)
    op.create_index('idx_provenance_created_at', 'provenance_events', ['created_at'], unique=False)
    op.create_index('idx_provenance_event_type', 'provenance_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_provenance_events_actor'), 'provenance_events', ['actor'], unique=False)
    op.create_index(op.f('ix_provenance_events_authority_id'), 'provenance_events', ['authority_id'], unique=False)
    op.create_index(op.f('ix_provenance_events_created_at'), 'provenance_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_provenance_events_event_type'), 'provenance_events', ['event_type'], unique=False)
    op.create_table('authority_delegations',
    sa.Column('delegation_id', sa.String(length=256), nullable=False),
    sa.Column('parent_authority_id', sa.String(length=256), nullable=False),
    sa.Column('child_authority_id', sa.String(length=256), nullable=False),
    sa.Column('actor', sa.String(length=256), nullable=False),
    sa.Column('delegated_to', sa.String(length=256), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_authority_id'], ['authorities.authority_id'], ),
    sa.ForeignKeyConstraint(['parent_authority_id'], ['authorities.authority_id'], ),
    sa.PrimaryKeyConstraint('delegation_id')
    )
    op.create_index('idx_delegation_actor', 'authority_delegations', ['actor'], unique=False)
    op.create_index('idx_delegation_created_at', 'authority_delegations', ['created_at'], unique=False)
    op.create_index('idx_delegation_delegated_to', 'authority_delegations', ['delegated_to'], unique=False)
    op.create_index(op.f('ix_authority_delegations_actor'), 'authority_delegations', ['actor'], unique=False)
    op.create_index(op.f('ix_authority_delegations_delegated_to'), 'authority_delegations', ['delegated_to'], unique=False)
    op.create_table('revocations',
    sa.Column('revocation_id', sa.String(length=256), nullable=False),
    sa.Column('authority_id', sa.String(length=256), nullable=False),
    sa.Column('actor', sa.String(length=256), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('cascades', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.authority_id'], ),
    sa.PrimaryKeyConstraint('revocation_id')
    )
    op.create_index('idx_revocation_actor', 'revocations', ['actor'], unique=False)
    op.create_index('idx_revocation_created_at', 'revocations', ['created_at'], unique=False)
    op.create_index(op.f('ix_revocations_actor'), 'revocations', ['actor'], unique=False)
    op.create_index(op.f('ix_revocations_created_at'), 'revocations', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revocations_created_at'), table_name='revocations')
    op.drop_index(op.f('ix_revocations_actor'), table_name='revocations')
    op.drop_index('idx_revocation_created_at', table_name='revocations')
    op.drop_index('idx_revocation_actor', table_name='revocations')
    op.drop_table('revocations')
    op.drop_index(op.f('ix_authority_delegations_delegated_to'), table_name='authority_delegations')
    op.drop_index(op.f('ix_authority_delegations_actor'), table_name='authority_delegations')
    op.drop_index('idx_delegation_delegated_to', table_name='authority_delegations')
    op.drop_index('idx_delegation_created_at', table_name='authority_delegations')
    op.drop_index('idx_delegation_actor', table_name='authority_delegations')
    op.drop_table('authority_delegations')
    op.drop_index(op.f('ix_provenance_events_event_type'), table_name='provenance_events')
    op.drop_index(op.f('ix_provenance_events_created_at'), table_name='provenance_events')
    op.drop_index(op.f('ix_provenance_events_authority_id'), table_name='provenance_events')
    op.drop_index(op.f('ix_provenance_events_actor'), table_name='provenance_events')
    op.drop_index('idx_provenance_event_type', table_name='provenance_events')
    op.drop_index('idx_provenance_created_at', table_name='provenance_events')
    op.drop_index('idx_provenance_authority', table_name='provenance_events')
    op.drop_index('idx_provenance_actor', table_name='provenance_events')
    op.drop_table('provenance_events')
    op.drop_index('idx_identity_type', table_name='identities')
    op.drop_index('idx_created_at', table_name='identities')
    op.drop_table('identities')
    op.drop_index(op.f('ix_authorization_logs_resource'), table_name='authorization_logs')
    op.drop_index(op.f('ix_authorization_logs_created_at'), table_name='authorization_logs')
    op.drop_index(op.f('ix_authorization_logs_actor'), table_name='authorization_logs')
    op.drop_index(op.f('ix_authorization_logs_action'), table_name='authorization_logs')
    op.drop_index('idx_authlog_resource', table_name='authorization_logs')
    op.drop_index('idx_authlog_decision', table_name='authorization_logs')
    op.drop_index('idx_authlog_created_at', table_name='authorization_logs')
    op.drop_index('idx_authlog_actor', table_name='authorization_logs')
    op.drop_index('idx_authlog_action', table_name='authorization_logs')
    op.drop_table('authorization_logs')
    op.drop_index(op.f('ix_authorities_sponsor'), table_name='authorities')
    op.drop_index(op.f('ix_authorities_issued_at'), table_name='authorities')
    op.drop_index(op.f('ix_authorities_expires_at'), table_name='authorities')
    op.drop_index(op.f('ix_authorities_actor'), table_name='authorities')
    op.drop_index('idx_authority_sponsor', table_name='authorities')
    op.drop_index('idx_authority_issued_at', table_name='authorities')
    op.drop_index('idx_authority_expires_at', table_name='authorities')
    op.drop_index('idx_authority_actor', table_name='authorities')
    op.drop_table('authorities')
    # ### end Alembic commands ###
